### ISSUE TITLE
could you please add external file/folder link to the list

### ISSUE THREAD

**Issue by telehan** [jivimberg/external-links#3]
links like [title](file:///PathToLocalFileOrFoler) is useful, it's that possible to add into the sidebar list

**Comment by jivimberg** [comment]
Just to confirm, do you mean listing links of the type:

- file:///path/to/file
- file:///path/to/folder

**Comment by telehan** [comment]
yes, local file links in markdown works like web link with `https://` replace by `file://`, it works in macOS, not sure for windows.
