### ISSUE TITLE
Option to show linked text with raw link alongside?

### ISSUE THREAD

**Issue by macintacos** [jivimberg/external-links#8]
Seeing all of the links in a note is fantastic. Sometimes I want to see what text is being used for a link, like for example for [this one](https://google.com) it would be nice to see something like

- https://google.com
  Text: "this one"

Or just something like that, doesn't have to be exactly the same.

Regardless, I appreciate the plugin! Thanks!

**Comment by jivimberg** [comment]
Hi Julian 👋  Thanks for the suggestion. I've been meaning to add the text label somewhere but couldn't find a design I like. I'll play some with it and see what works best.

**Comment by jivimberg** [comment]
Fixed! Let me know your thoughts
